"""empty message

Revision ID: 123b370caf8b
Revises: 448f716ad346
Create Date: 2024-07-24 21:56:43.494770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '123b370caf8b'
down_revision: Union[str, None] = '448f716ad346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'int_id',
                    existing_type=sa.VARCHAR(length=16),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'int_id',
                    existing_type=sa.VARCHAR(length=16),
                    nullable=False)
    # ### end Alembic commands ###
