"""empty message

Revision ID: 448f716ad346
Revises: e97c27c2ede2
Create Date: 2024-07-24 21:56:06.667557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448f716ad346'
down_revision: Union[str, None] = 'e97c27c2ede2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'log', ['pk'])
    op.alter_column('message', 'id',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.create_unique_constraint(None, 'message', ['pk'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='unique')
    op.alter_column('message', 'id',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.drop_constraint(None, 'log', type_='unique')
    # ### end Alembic commands ###
